export const LightTheme = {
    bg: '#f5f5f7',
    bgCard: '#ffffff',
    bgSecondary: '#ffffff',
    bgMuted: '#f0f0f2',
    text: '#1d1d1f',
    textSecondary: '#86868b',
    textTertiary: '#6e6e73',
    accent: '#0071e3',
    accentLight: 'rgba(0, 113, 227, 0.12)',
    success: '#34c759',
    successLight: 'rgba(52, 199, 89, 0.12)',
    danger: '#ff3b30',
    dangerLight: 'rgba(255, 59, 48, 0.12)',
    warning: '#ff9500',
    warningLight: 'rgba(255, 149, 0, 0.12)',
    border: 'rgba(0, 0, 0, 0.06)',
    shadow: '#000',
    statusBar: 'dark',
};

export const DarkTheme = {
    bg: '#000000',
    bgCard: '#1c1c1e',
    bgSecondary: '#1c1c1e',
    bgMuted: '#2c2c2e',
    text: '#f5f5f7',
    textSecondary: '#98989d',
    textTertiary: '#8e8e93',
    accent: '#0a84ff',
    accentLight: 'rgba(10, 132, 255, 0.15)',
    success: '#30d158',
    successLight: 'rgba(48, 209, 88, 0.15)',
    danger: '#ff453a',
    dangerLight: 'rgba(255, 69, 58, 0.15)',
    warning: '#ff9f0a',
    warningLight: 'rgba(255, 159, 10, 0.15)',
    border: 'rgba(255, 255, 255, 0.08)',
    shadow: '#000',
    statusBar: 'light',
};

// ESPN CDN sirve PNG, compatible con React Native Image
export const NBA_TEAM_LOGOS = {
    'Atlanta Hawks': 'https://a.espncdn.com/i/teamlogos/nba/500/atl.png',
    'Boston Celtics': 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png',
    'Brooklyn Nets': 'https://a.espncdn.com/i/teamlogos/nba/500/bkn.png',
    'Charlotte Hornets': 'https://a.espncdn.com/i/teamlogos/nba/500/cha.png',
    'Chicago Bulls': 'https://a.espncdn.com/i/teamlogos/nba/500/chi.png',
    'Cleveland Cavaliers': 'https://a.espncdn.com/i/teamlogos/nba/500/cle.png',
    'Dallas Mavericks': 'https://a.espncdn.com/i/teamlogos/nba/500/dal.png',
    'Denver Nuggets': 'https://a.espncdn.com/i/teamlogos/nba/500/den.png',
    'Detroit Pistons': 'https://a.espncdn.com/i/teamlogos/nba/500/det.png',
    'Golden State Warriors': 'https://a.espncdn.com/i/teamlogos/nba/500/gs.png',
    'Houston Rockets': 'https://a.espncdn.com/i/teamlogos/nba/500/hou.png',
    'Indiana Pacers': 'https://a.espncdn.com/i/teamlogos/nba/500/ind.png',
    'LA Clippers': 'https://a.espncdn.com/i/teamlogos/nba/500/lac.png',
    'Los Angeles Clippers': 'https://a.espncdn.com/i/teamlogos/nba/500/lac.png',
    'Los Angeles Lakers': 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
    'Memphis Grizzlies': 'https://a.espncdn.com/i/teamlogos/nba/500/mem.png',
    'Miami Heat': 'https://a.espncdn.com/i/teamlogos/nba/500/mia.png',
    'Milwaukee Bucks': 'https://a.espncdn.com/i/teamlogos/nba/500/mil.png',
    'Minnesota Timberwolves': 'https://a.espncdn.com/i/teamlogos/nba/500/min.png',
    'New Orleans Pelicans': 'https://a.espncdn.com/i/teamlogos/nba/500/no.png',
    'New York Knicks': 'https://a.espncdn.com/i/teamlogos/nba/500/ny.png',
    'Oklahoma City Thunder': 'https://a.espncdn.com/i/teamlogos/nba/500/okc.png',
    'Orlando Magic': 'https://a.espncdn.com/i/teamlogos/nba/500/orl.png',
    'Philadelphia 76ers': 'https://a.espncdn.com/i/teamlogos/nba/500/phi.png',
    'Phoenix Suns': 'https://a.espncdn.com/i/teamlogos/nba/500/phx.png',
    'Portland Trail Blazers': 'https://a.espncdn.com/i/teamlogos/nba/500/por.png',
    'Sacramento Kings': 'https://a.espncdn.com/i/teamlogos/nba/500/sac.png',
    'San Antonio Spurs': 'https://a.espncdn.com/i/teamlogos/nba/500/sa.png',
    'Toronto Raptors': 'https://a.espncdn.com/i/teamlogos/nba/500/tor.png',
    'Utah Jazz': 'https://a.espncdn.com/i/teamlogos/nba/500/utah.png',
    'Washington Wizards': 'https://a.espncdn.com/i/teamlogos/nba/500/wsh.png',
};
